create table ontology_definition (
   "ID"               NUMBER(15,0) CONSTRAINT "NOT_NULL_ODEF_ID" NOT NULL ENABLE,
   "COMPOUND_ID"      NUMBER(15,0) CONSTRAINT "NOT_NULL_ODEF_COMP_ID" NOT NULL ENABLE,
   "DEFINITION"       CLOB,
   "STATUS"  CHAR(1 BYTE) CONSTRAINT "NOT_NULL_ODEF_STATUS" NOT NULL ENABLE

--    CONSTRAINT "FK_ODEF_TO_COMPOUND" FOREIGN KEY ("COMPOUND_ID") REFERENCES "CHEBI"."COMPOUNDS" ("ID")
);
